name: CMake Build & Tests

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    name: ${{ matrix.name }}

    strategy:
      fail-fast: false

      matrix:
        include:
          # Windows / MSVC 2022
          - os: windows-2022
            name: Windows / MSVC 2022
            preset: windows-vs2022-debug

          # Windows / MSVC 2026
          - os: windows-2025-vs2026
            name: Windows / MSVC 2026
            preset: windows-vs2026-debug

          # Linux / GCC
          - os: ubuntu-latest
            name: Linux / GCC
            preset: linux-gcc-debug

          # Linux / Clang
          - os: ubuntu-latest
            name: Linux / Clang
            preset: linux-clang-debug

          # macOS / Apple Clang
          - os: macos-latest
            name: macOS / Apple Clang
            preset: macos-clang-debug

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }} -j

      - name: Run tests
        run: ctest --preset ${{ matrix.preset }} --output-on-failure
